// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iouphlbcvvicsivgkgfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvdXBobGJjdnZpY3NpdmdrZ2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTg0OTgsImV4cCI6MjA2ODY5NDQ5OH0.vhBqS4PSLtHD1BSxd8t-bB51HPdRn3trvgwpcAAPe5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});